name: Frontend CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Frontend image build
        run: |
          docker build -t vite-frontend .

      - name: Verify container health
        run: |
          docker run -d -p 8080:80 --name test-frontend vite-frontend
          sleep 5
          curl -f http://localhost:8080 || (echo "Unhealthy container" && exit 1)

      - name: Clean up container
        run: |
          docker stop test-frontend && docker rm test-frontend
        
      - name: Deploy on Render
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
